### ISSUE TITLE
Image generation and reading problem

### ISSUE THREAD

**Issue by SaSa709** [XiwenChen-Clemson/DH-GAN#1]
Hello, when I ran the code, I would get the error "OSError: cannot write mode F as BMP", so I changed the generated image format to .tif format, but a new problem appeared "PIL.UnidentifiedImageError: cannot identify image file 'E:\\lianxi\\DH-GAN-main\\DH-GAN-main\\gray.tif'", the image I generated cannot be opened. There is no problem with the image path. Have you encountered this kind of problem? Problem? My guess is that the image I generated is corrupted. In addition, I would also like to ask if you can provide the compressed package of your experimental environment. I feel that the version mismatch of the environment package may cause problems. I look forward to your reply. Thank you very much!

**Comment by xiwenc1** [comment]
I guess it is due to the new version of ```skimage``` and now it only supports saving the image with dtype uint8, so you can try this way:
```
img = ...
img_s = (255.*img).astype(np.uint8)
imsave(join(args.save_dir,'./gray.bmp'),np.squeeze(img_s))
```

We provide an updated version in ```https://github.com/maxgray2056/DigitalHolography/tree/main``` but in this repo, dhgan is only for real data, and the version for simulated data will be available soon.

Also, feel free to email me with any further problems (xiwenc@g.clemson.edu). Thanks for your interest in our work!

**Comment by SaSa709** [comment]
Received, thank you very much for your reply! Looking forward to the update of the simulated data version!

**Comment by xiwenc1** [comment]
I think that version is available now, and you can try it in that repo I mentioned before. Please feel free to contact me if you have further problems.
